### ISSUE TITLE
application.json examples do not work in appregistry

### ISSUE THREAD

**Issue by BerndGewehr** [ibmcnxdev/verse-developer-chrome-ext#5] opened 2017-01-13 08:13 UTC
The examples from the reference
https://ibmcnxdev.github.io/verse-developer-chrome-ext/reference/reference.html

Sample 1
Sample 2
Sample 3

do not work when trying to upload them as organizational extensions. The save button does not save and close as expected but the second click on save closes the window without save. No error message at all. No new extension.

**Comment by markewallace** [comment] 2017-01-25 08:02
@maire-kehoe I'm seeing the same issue, were can we find error details if a json file cannot be uploaded?

**Comment by maire-kehoe** [comment] 2017-01-25 14:44
@BerndGewehr @markewallace I've logged this issue as:
OCS Defect 212205: AppRegistry, UI silently fails on bad JSON
The problem is in the AppRegistry / Organization Extensions page UI, in the code where it tries to determine whether the extension is a communities, Verse or old-style extension (Profiles, Files, Contacts, etc). It is silently failing if it cannot recognize it as one of the known types of extension. 

To workaround, ensure that the file contains an object { }  instead of an array [ ], and ensure the object
contains an attribute named "app_id": 
Also note that Sample 1, 2, 3 links are linking to the files:
https://github.com/ibmcnxdev/verse-developer-chrome-ext/blob/master/src/applications.json
https://github.com/ibmcnxdev/verse-developer-chrome-ext/blob/master/tutorial/step3/applications.json
https://github.com/ibmcnxdev/verse-developer-chrome-ext/blob/master/tutorial/step4/applications.json

which are using the chrome extension syntax, instead of the AppRegistry syntax. 
To convert the files to the AppRegistry syntax, use the instructions in the previous comment on Issue #3:
https://github.com/ibmcnxdev/verse-developer-chrome-ext/issues/3#issuecomment-272845645

**Comment by markewallace** [comment] 2017-01-25 15:27
thanks @maire-kehoe

**Comment by BerndGewehr** [comment] 2017-03-29 14:51
As this is an issue in the app registry, when will it be fixed?

**Comment by maire-kehoe** [comment] 2017-03-29 16:30
@BerndGewehr In our test environments the issue
OCS Defect 212205: AppRegistry, UI silently fails on bad JSON
has been indirectly fixed by some improvements to the error handling, 
with the change planned to be released in May.

**Comment by BerndGewehr** [comment] 2017-03-29 16:35
Great news, thank you!

**Closed** 2017-03-29 21:00 UTC
